# Generated by Django 5.0.3 on 2024-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_testsentiment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsentiment',
            name='review',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
